# Generated by Django 5.2.7 on 2025-10-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('release_date', models.CharField(max_length=99)),
                ('vote_avg', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('poster_path', models.CharField(max_length=255)),
                ('genre_ids', models.ManyToManyField(to='server.genre')),
            ],
        ),
    ]
