# Generated by Django 5.2.7 on 2025-10-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='vote_avg',
            new_name='vote_average',
        ),
    ]
